/*******************************************************************************
 * Copyright 2012
 * Ubiquitous Knowledge Processing (UKP) Lab
 * Technische Universität Darmstadt
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package de.tudarmstadt.ukp.lmf.model.enums;

/**
 * Enumeration of unique language identifiers specified in ISO 639.
 * @author Zijad Maksuti
 * @author Christian M. Meyer
 */
public final class ELanguageIdentifier {

	/** @deprecated Use {@link #ENGLISH} instead. */
	@Deprecated
	public static final String en = "eng";
	/** @deprecated Use {@link #GERMAN} instead. */
	@Deprecated
	public static final String de = "deu";
	
	public static final String ENGLISH = "eng";
	public static final String GERMAN = "deu";
		
	public static final String ISO639_AAA = "aaa"; // Ghotuo
	public static final String ISO639_AAB = "aab"; // Alumu-Tesu
	public static final String ISO639_AAE = "aae"; // Arbëreshë Albanian
	public static final String ISO639_AAK = "aak"; // Ankave
	public static final String ISO639_AAR = "aar"; // Afar
	public static final String ISO639_AAT = "aat"; // Arvanitika Albanian
	public static final String ISO639_ABA = "aba"; // Abé
	public static final String ISO639_ABE = "abe"; // Western Abnaki
	public static final String ISO639_ABK = "abk"; // Abkhazian
	public static final String ISO639_ABM = "abm"; // Abanyom
	public static final String ISO639_ABQ = "abq"; // Abaza
	public static final String ISO639_ACE = "ace"; // Achinese
	public static final String ISO639_ACH = "ach"; // Acoli
	public static final String ISO639_ACR = "acr"; // Achi
	public static final String ISO639_ACV = "acv"; // Achumawi
	public static final String ISO639_ADA = "ada"; // Adangme
	public static final String ISO639_ADE = "ade"; // Adele
	public static final String ISO639_ADJ = "adj"; // Adioukrou
	public static final String ISO639_ADT = "adt"; // Adnyamathanha
	public static final String ISO639_ADY = "ady"; // Adyghe
	public static final String ISO639_ADZ = "adz"; // Adzera
	public static final String ISO639_AER = "aer"; // Eastern Arrernte
	public static final String ISO639_AFH = "afh"; // Afrihili
	public static final String ISO639_AFR = "afr"; // Afrikaans
	public static final String ISO639_AGU = "agu"; // Aguacateco
	public static final String ISO639_AGX = "agx"; // Aghul
	public static final String ISO639_AIN = "ain"; // Ainu (Japan)
	public static final String ISO639_AIW = "aiw"; // Aari
	public static final String ISO639_AKA = "aka"; // Akan
	public static final String ISO639_AKE = "ake"; // Akawaio
	public static final String ISO639_AKK = "akk"; // Akkadian
	public static final String ISO639_AKL = "akl"; // Aklanon
	public static final String ISO639_AKR = "akr"; // Araki
	public static final String ISO639_AKZ = "akz"; // Alabama
	public static final String ISO639_ALC = "alc"; // Qawasqar
	public static final String ISO639_ALE = "ale"; // Aleut
	public static final String ISO639_ALI = "ali"; // Amaimon
	public static final String ISO639_ALN = "aln"; // Gheg Albanian
	public static final String ISO639_ALQ = "alq"; // Algonquin
	public static final String ISO639_ALS = "als"; // Tosk Albanian
	public static final String ISO639_AMH = "amh"; // Amharic
	public static final String ISO639_AMK = "amk"; // Ambai
	public static final String ISO639_AMN = "amn"; // Amanab
	public static final String ISO639_AMS = "ams"; // Southern Amami-Oshima
	public static final String ISO639_AMT = "amt"; // Amto
	public static final String ISO639_AMU = "amu"; // Guerrero Amuzgo
	public static final String ISO639_AND = "and"; // Ansus
	public static final String ISO639_ANG = "ang"; // Old English
	public static final String ISO639_ANT = "ant"; // Antakarinya
	public static final String ISO639_APC = "apc"; // North Levantine Arabic
	public static final String ISO639_APJ = "apj"; // Jicarilla Apache
	public static final String ISO639_APK = "apk"; // Kiowa Apache
	public static final String ISO639_APL = "apl"; // Lipan Apache
	public static final String ISO639_APM = "apm"; // Mescalero-Chiricahua Apache
	public static final String ISO639_APW = "apw"; // Western Apache
	public static final String ISO639_APY = "apy"; // Apalaí
	public static final String ISO639_ARA = "ara"; // Arabic
	public static final String ISO639_ARB = "arb"; // Standard Arabic
	public static final String ISO639_ARC = "arc"; // Aramaic
	public static final String ISO639_ARG = "arg"; // Aragonese
	public static final String ISO639_ARN = "arn"; // Mapudungun
	public static final String ISO639_ARP = "arp"; // Arapaho
	public static final String ISO639_ARS = "ars"; // Najdi Arabic
	public static final String ISO639_ARU = "aru"; // Aruá (Amazonas State)
	public static final String ISO639_ARW = "arw"; // Arawak
	public static final String ISO639_ARZ = "arz"; // Egyptian Arabic
	public static final String ISO639_ASM = "asm"; // Assamese
	public static final String ISO639_AST = "ast"; // Asturian
	public static final String ISO639_AVA = "ava"; // Avaric
	public static final String ISO639_AVE = "ave"; // Avestan
	public static final String ISO639_AVK = "avk"; // Kotava
	public static final String ISO639_AWA = "awa"; // Awadhi
	public static final String ISO639_AWK = "awk"; // Awabakal
	public static final String ISO639_AYM = "aym"; // Aymara
	public static final String ISO639_AZB = "azb"; // South Azerbaijani
	public static final String ISO639_AZE = "aze"; // Azerbaijani
	public static final String ISO639_BAK = "bak"; // Bashkir
	public static final String ISO639_BAL = "bal"; // Baluchi
	public static final String ISO639_BAM = "bam"; // Bambara
	public static final String ISO639_BAN = "ban"; // Balinese
	public static final String ISO639_BAR = "bar"; // Bavarian
	public static final String ISO639_BAS = "bas"; // Basa (Cameroon)
	public static final String ISO639_BCC = "bcc"; // Southern Balochi
	public static final String ISO639_BCZ = "bcz"; // Bainouk-Gunyaamolo
	public static final String ISO639_BDY = "bdy"; // Bandjalang
	public static final String ISO639_BEJ = "bej"; // Beja
	public static final String ISO639_BEL = "bel"; // Belarusian
	public static final String ISO639_BEM = "bem"; // Bemba (Zambia)
	public static final String ISO639_BEN = "ben"; // Bengali
	public static final String ISO639_BEW = "bew"; // Betawi
	public static final String ISO639_BHO = "bho"; // Bhojpuri
	public static final String ISO639_BHW = "bhw"; // Biak
	public static final String ISO639_BIK = "bik"; // Bikol
	public static final String ISO639_BIN = "bin"; // Bini
	public static final String ISO639_BIS = "bis"; // Bislama
	public static final String ISO639_BJZ = "bjz"; // Baruga
	public static final String ISO639_BNG = "bng"; // Benga
	public static final String ISO639_BNS = "bns"; // Bundeli
	public static final String ISO639_BOD = "bod"; // Tibetan
	public static final String ISO639_BOS = "bos"; // Bosnian
	public static final String ISO639_BOT = "bot"; // Bongo
	public static final String ISO639_BPL = "bpl"; // Broome Pearling Lugger Pidgin
	public static final String ISO639_BPY = "bpy"; // Bishnupriya
	public static final String ISO639_BQI = "bqi"; // Bakhtiari
	public static final String ISO639_BRA = "bra"; // Braj
	public static final String ISO639_BRC = "brc"; // Berbice Creole Dutch
	public static final String ISO639_BRE = "bre"; // Breton
	public static final String ISO639_BUG = "bug"; // Buginese
	public static final String ISO639_BUL = "bul"; // Bulgarian
	public static final String ISO639_BXR = "bxr"; // Russia Buriat
	public static final String ISO639_BYN = "byn"; // Bilin
	public static final String ISO639_BZT = "bzt"; // Brithenig
	public static final String ISO639_CAA = "caa"; // Chortí
	public static final String ISO639_CAC = "cac"; // Chuj
	public static final String ISO639_CAK = "cak"; // Kaqchikel
	public static final String ISO639_CAT = "cat"; // Catalan
	public static final String ISO639_CDO = "cdo"; // Min Dong Chinese
	public static final String ISO639_CEB = "ceb"; // Cebuano
	public static final String ISO639_CES = "ces"; // Czech
	public static final String ISO639_CHA = "cha"; // Chamorro
	public static final String ISO639_CHC = "chc"; // Catawba
	public static final String ISO639_CHE = "che"; // Chechen
	public static final String ISO639_CHF = "chf"; // Tabasco Chontal
	public static final String ISO639_CHK = "chk"; // Chuukese
	public static final String ISO639_CHM = "chm"; // Mari (Russia)
	public static final String ISO639_CHO = "cho"; // Choctaw
	public static final String ISO639_CHR = "chr"; // Cherokee
	public static final String ISO639_CHU = "chu"; // Church Slavic
	public static final String ISO639_CHV = "chv"; // Chuvash
	public static final String ISO639_CHY = "chy"; // Cheyenne
	public static final String ISO639_CIC = "cic"; // Chickasaw
	public static final String ISO639_CJY = "cjy"; // Jinyu Chinese
	public static final String ISO639_CKB = "ckb"; // Central Kurdish
	public static final String ISO639_COB = "cob"; // Chicomuceltec
	public static final String ISO639_COM = "com"; // Comanche
	public static final String ISO639_COP = "cop"; // Coptic
	public static final String ISO639_COR = "cor"; // Cornish
	public static final String ISO639_COS = "cos"; // Corsican
	public static final String ISO639_CPG = "cpg"; // Cappadocian Greek
	public static final String ISO639_CPX = "cpx"; // Pu-Xian Chinese
	public static final String ISO639_CRE = "cre"; // Cree
	public static final String ISO639_CRH = "crh"; // Crimean Tatar
	public static final String ISO639_CSB = "csb"; // Kashubian
	public static final String ISO639_CTU = "ctu"; // Chol
	public static final String ISO639_CUK = "cuk"; // San Blas Kuna
	public static final String ISO639_CYM = "cym"; // Welsh
	public static final String ISO639_CZH = "czh"; // Huizhou Chinese
	public static final String ISO639_CZO = "czo"; // Min Zhong Chinese
	public static final String ISO639_DAN = "dan"; // Danish
	public static final String ISO639_DAR = "dar"; // Dargwa
	public static final String ISO639_DAV = "dav"; // Taita
	public static final String ISO639_DBL = "dbl"; // Dyirbal
	public static final String ISO639_DEU = "deu"; // German
	public static final String ISO639_DIF = "dif"; // Dieri
	public static final String ISO639_DIM = "dim"; // Dime
	public static final String ISO639_DIU = "diu"; // Diriku
	public static final String ISO639_DIV = "div"; // Dhivehi
	public static final String ISO639_DLM = "dlm"; // Dalmatian
	public static final String ISO639_DRL = "drl"; // Paakantyi
	public static final String ISO639_DSB = "dsb"; // Lower Sorbian
	public static final String ISO639_DSN = "dsn"; // Dusner
	public static final String ISO639_DUJ = "duj"; // Dhuwal
	public static final String ISO639_DUM = "dum"; // Middle Dutch
	public static final String ISO639_DZO = "dzo"; // Dzongkha
	public static final String ISO639_EGY = "egy"; // Egyptian
	public static final String ISO639_ELL = "ell"; // Greek
	public static final String ISO639_ENG = "eng"; // English
	public static final String ISO639_ENM = "enm"; // Middle English
	public static final String ISO639_EPO = "epo"; // Esperanto
	public static final String ISO639_EST = "est"; // Estonian
	public static final String ISO639_ESU = "esu"; // Central Yupik
	public static final String ISO639_EUS = "eus"; // Basque
	public static final String ISO639_EWE = "ewe"; // Ewe
	public static final String ISO639_EXT = "ext"; // Extremaduran
	public static final String ISO639_FAN = "fan"; // Fang (Equatorial Guinea)
	public static final String ISO639_FAO = "fao"; // Faroese
	public static final String ISO639_FAS = "fas"; // Persian
	public static final String ISO639_FIJ = "fij"; // Fijian
	public static final String ISO639_FIL = "fil"; // Filipino
	public static final String ISO639_FIN = "fin"; // Finnish
	public static final String ISO639_FON = "fon"; // Fon
	public static final String ISO639_FRA = "fra"; // French
	public static final String ISO639_FRM = "frm"; // Middle French
	public static final String ISO639_FRO = "fro"; // Old French
	public static final String ISO639_FRP = "frp"; // Arpitan
	public static final String ISO639_FRY = "fry"; // Western Frisian
	public static final String ISO639_FUD = "fud"; // East Futuna
	public static final String ISO639_FUL = "ful"; // Fulah
	public static final String ISO639_FUR = "fur"; // Friulian
	public static final String ISO639_GAA = "gaa"; // Ga
	public static final String ISO639_GAN = "gan"; // Gan Chinese
	public static final String ISO639_GAY = "gay"; // Gayo
	public static final String ISO639_GIL = "gil"; // Gilbertese
	public static final String ISO639_GLA = "gla"; // Scottish Gaelic
	public static final String ISO639_GLE = "gle"; // Irish
	public static final String ISO639_GLG = "glg"; // Galician
	public static final String ISO639_GLK = "glk"; // Gilaki
	public static final String ISO639_GLV = "glv"; // Manx
	public static final String ISO639_GMH = "gmh"; // Middle High German
	public static final String ISO639_GML = "gml"; // Middle Low German
	public static final String ISO639_GMY = "gmy"; // Mycenaean Greek
	public static final String ISO639_GND = "gnd"; // Zulgo-Gemzek
	public static final String ISO639_GNI = "gni"; // Gooniyandi
	public static final String ISO639_GOH = "goh"; // Old High German
	public static final String ISO639_GOT = "got"; // Gothic
	public static final String ISO639_GRC = "grc"; // Ancient Greek
	public static final String ISO639_GRN = "grn"; // Guarani
	public static final String ISO639_GSW = "gsw"; // Swiss German
	public static final String ISO639_GUJ = "guj"; // Gujarati
	public static final String ISO639_GUT = "gut"; // Maléku Jaíka
	public static final String ISO639_HAK = "hak"; // Hakka Chinese
	public static final String ISO639_HAT = "hat"; // Haitian
	public static final String ISO639_HAU = "hau"; // Hausa
	public static final String ISO639_HAW = "haw"; // Hawaiian
	public static final String ISO639_HBS = "hbs"; // Serbo-Croatian
	public static final String ISO639_HEB = "heb"; // Hebrew
	public static final String ISO639_HER = "her"; // Herero
	public static final String ISO639_HIF = "hif"; // Fiji Hindi
	public static final String ISO639_HIL = "hil"; // Hiligaynon
	public static final String ISO639_HIN = "hin"; // Hindi
	public static final String ISO639_HIT = "hit"; // Hittite
	public static final String ISO639_HMN = "hmn"; // Hmong
	public static final String ISO639_HMO = "hmo"; // Hiri Motu
	public static final String ISO639_HOI = "hoi"; // Holikachuk
	public static final String ISO639_HRV = "hrv"; // Croatian
	public static final String ISO639_HSB = "hsb"; // Upper Sorbian
	public static final String ISO639_HSN = "hsn"; // Xiang Chinese
	public static final String ISO639_HUH = "huh"; // Huilliche
	public static final String ISO639_HUN = "hun"; // Hungarian
	public static final String ISO639_HUS = "hus"; // Huastec
	public static final String ISO639_HWC = "hwc"; // Hawai'i Creole English
	public static final String ISO639_HYE = "hye"; // Armenian
	public static final String ISO639_IBA = "iba"; // Iban
	public static final String ISO639_IBO = "ibo"; // Igbo
	public static final String ISO639_IDO = "ido"; // Ido
	public static final String ISO639_III = "iii"; // Sichuan Yi
	public static final String ISO639_IKU = "iku"; // Inuktitut
	public static final String ISO639_ILE = "ile"; // Interlingue
	public static final String ISO639_ILO = "ilo"; // Iloko
	public static final String ISO639_INA = "ina"; // Interlingua
	public static final String ISO639_IND = "ind"; // Indonesian
	public static final String ISO639_INH = "inh"; // Ingush
	public static final String ISO639_IPK = "ipk"; // Inupiaq
	public static final String ISO639_ISH = "ish"; // Esan
	public static final String ISO639_ISL = "isl"; // Icelandic
	public static final String ISO639_ITA = "ita"; // Italian
	public static final String ISO639_IXL = "ixl"; // Ixil
	public static final String ISO639_JAC = "jac"; // Popti'
	public static final String ISO639_JAM = "jam"; // Jamaican Creole English
	public static final String ISO639_JAO = "jao"; // Yanyuwa
	public static final String ISO639_JAV = "jav"; // Javanese
	public static final String ISO639_JBO = "jbo"; // Lojban
	public static final String ISO639_JIV = "jiv"; // Shuar
	public static final String ISO639_JPA = "jpa"; // Jewish Palestinian Aramaic
	public static final String ISO639_JPN = "jpn"; // Japanese
	public static final String ISO639_JPR = "jpr"; // Judeo-Persian
	public static final String ISO639_JRB = "jrb"; // Judeo-Arabic
	public static final String ISO639_KAA = "kaa"; // Kara-Kalpak
	public static final String ISO639_KAB = "kab"; // Kabyle
	public static final String ISO639_KAC = "kac"; // Kachin
	public static final String ISO639_KAL = "kal"; // Kalaallisut
	public static final String ISO639_KAM = "kam"; // Kamba (Kenya)
	public static final String ISO639_KAN = "kan"; // Kannada
	public static final String ISO639_KAS = "kas"; // Kashmiri
	public static final String ISO639_KAT = "kat"; // Georgian
	public static final String ISO639_KAU = "kau"; // Kanuri
	public static final String ISO639_KAW = "kaw"; // Kawi
	public static final String ISO639_KAZ = "kaz"; // Kazakh
	public static final String ISO639_KBC = "kbc"; // Kadiwéu
	public static final String ISO639_KBF = "kbf"; // Kakauhua
	public static final String ISO639_KDA = "kda"; // Worimi
	public static final String ISO639_KDD = "kdd"; // Yankunytjatjara
	public static final String ISO639_KEA = "kea"; // Kabuverdianu
	public static final String ISO639_KEB = "keb"; // Kélé
	public static final String ISO639_KEK = "kek"; // Kekchí
	public static final String ISO639_KHK = "khk"; // Halh Mongolian
	public static final String ISO639_KHM = "khm"; // Central Khmer
	public static final String ISO639_KIK = "kik"; // Kikuyu
	public static final String ISO639_KIN = "kin"; // Kinyarwanda
	public static final String ISO639_KIR = "kir"; // Kirghiz
	public static final String ISO639_KJB = "kjb"; // Q'anjob'al
	public static final String ISO639_KJR = "kjr"; // Kurudu
	public static final String ISO639_KKY = "kky"; // Guguyimidjir
	public static final String ISO639_KLD = "kld"; // Gamilaraay
	public static final String ISO639_KLN = "kln"; // Kalenjin
	public static final String ISO639_KMR = "kmr"; // Northern Kurdish
	public static final String ISO639_KNJ = "knj"; // Western Kanjobal
	public static final String ISO639_KNW = "knw"; // Kung-Ekoka
	public static final String ISO639_KOK = "kok"; // Konkani
	public static final String ISO639_KOM = "kom"; // Komi
	public static final String ISO639_KON = "kon"; // Kongo
	public static final String ISO639_KOR = "kor"; // Korean
	public static final String ISO639_KPG = "kpg"; // Kapingamarangi
	public static final String ISO639_KRC = "krc"; // Karachay-Balkar
	public static final String ISO639_KRL = "krl"; // Karelian
	public static final String ISO639_KSH = "ksh"; // Kölsch
	public static final String ISO639_KSI = "ksi"; // Krisa
	public static final String ISO639_KTN = "ktn"; // Karitiâna
	public static final String ISO639_KUA = "kua"; // Kuanyama
	public static final String ISO639_KUD = "kud"; // 'Auhelawa
	public static final String ISO639_KUR = "kur"; // Kurdish
	public static final String ISO639_KYI = "kyi"; // Kiput
	public static final String ISO639_KZG = "kzg"; // Kikai
	public static final String ISO639_LAC = "lac"; // Lacandon
	public static final String ISO639_LAD = "lad"; // Ladino
	public static final String ISO639_LAH = "lah"; // Lahnda
	public static final String ISO639_LAM = "lam"; // Lamba
	public static final String ISO639_LAO = "lao"; // Lao
	public static final String ISO639_LAT = "lat"; // Latin
	public static final String ISO639_LAV = "lav"; // Latvian
	public static final String ISO639_LBE = "lbe"; // Lak
	public static final String ISO639_LEZ = "lez"; // Lezghian
	public static final String ISO639_LFN = "lfn"; // Lingua Franca Nova
	public static final String ISO639_LIJ = "lij"; // Ligurian
	public static final String ISO639_LIM = "lim"; // Limburgan
	public static final String ISO639_LIN = "lin"; // Lingala
	public static final String ISO639_LIT = "lit"; // Lithuanian
	public static final String ISO639_LIV = "liv"; // Liv
	public static final String ISO639_LKT = "lkt"; // Lakota
	public static final String ISO639_LLD = "lld"; // Ladin
	public static final String ISO639_LMO = "lmo"; // Lombard
	public static final String ISO639_LNG = "lng"; // Langobardic
	public static final String ISO639_LTG = "ltg"; // Latgalian
	public static final String ISO639_LTZ = "ltz"; // Luxembourgish
	public static final String ISO639_LUA = "lua"; // Luba-Lulua
	public static final String ISO639_LUB = "lub"; // Luba-Katanga
	public static final String ISO639_LUG = "lug"; // Ganda
	public static final String ISO639_LUN = "lun"; // Lunda
	public static final String ISO639_LUO = "luo"; // Luo (Kenya and Tanzania)
	public static final String ISO639_LUY = "luy"; // Luyia
	public static final String ISO639_LVK = "lvk"; // Lavukaleve
	public static final String ISO639_MAH = "mah"; // Marshallese
	public static final String ISO639_MAL = "mal"; // Malayalam
	public static final String ISO639_MAM = "mam"; // Mam
	public static final String ISO639_MAN = "man"; // Mandingo
	public static final String ISO639_MAR = "mar"; // Marathi
	public static final String ISO639_MAS = "mas"; // Masai
	public static final String ISO639_MDF = "mdf"; // Moksha
	public static final String ISO639_MEN = "men"; // Mende (Sierra Leone)
	public static final String ISO639_MGA = "mga"; // Middle Irish
	public static final String ISO639_MGH = "mgh"; // Makhuwa-Meetto
	public static final String ISO639_MHC = "mhc"; // Mocho
	public static final String ISO639_MHR = "mhr"; // Eastern Mari
	public static final String ISO639_MIQ = "miq"; // Mískito
	public static final String ISO639_MKD = "mkd"; // Macedonian
	public static final String ISO639_MLG = "mlg"; // Malagasy
	public static final String ISO639_MLT = "mlt"; // Maltese
	public static final String ISO639_MMP = "mmp"; // Siawi
	public static final String ISO639_MNC = "mnc"; // Manchu
	public static final String ISO639_MNK = "mnk"; // Mandinka
	public static final String ISO639_MNP = "mnp"; // Min Bei Chinese
	public static final String ISO639_MNS = "mns"; // Mansi
	public static final String ISO639_MOD = "mod"; // Mobilian
	public static final String ISO639_MON = "mon"; // Mongolian
	public static final String ISO639_MOP = "mop"; // Mopán Maya
	public static final String ISO639_MOS = "mos"; // Mossi
	public static final String ISO639_MPS = "mps"; // Dadibi
	public static final String ISO639_MRI = "mri"; // Maori
	public static final String ISO639_MRJ = "mrj"; // Western Mari
	public static final String ISO639_MRV = "mrv"; // Mangareva
	public static final String ISO639_MSA = "msa"; // Malay
	public static final String ISO639_MUL = "mul"; // Multiple languages
	public static final String ISO639_MUS = "mus"; // Creek
	public static final String ISO639_MWL = "mwl"; // Mirandese
	public static final String ISO639_MWP = "mwp"; // Kala Lagaw Ya
	public static final String ISO639_MYA = "mya"; // Burmese
	public static final String ISO639_MYV = "myv"; // Erzya
	public static final String ISO639_NAN = "nan"; // Min Nan Chinese
	public static final String ISO639_NAP = "nap"; // Neapolitan
	public static final String ISO639_NAU = "nau"; // Nauru
	public static final String ISO639_NAV = "nav"; // Navajo
	public static final String ISO639_NBL = "nbl"; // South Ndebele
	public static final String ISO639_NCI = "nci"; // Classical Nahuatl
	public static final String ISO639_NDE = "nde"; // North Ndebele
	public static final String ISO639_NDO = "ndo"; // Ndonga
	public static final String ISO639_NDS = "nds"; // Low German
	public static final String ISO639_NEP = "nep"; // Nepali
	public static final String ISO639_NEW = "new"; // Newari
	public static final String ISO639_NHX = "nhx"; // Isthmus-Mecayapan Nahuatl
	public static final String ISO639_NIU = "niu"; // Niuean
	public static final String ISO639_NLD = "nld"; // Dutch
	public static final String ISO639_NMN = "nmn"; // !Xóõ
	public static final String ISO639_NNO = "nno"; // Norwegian Nynorsk
	public static final String ISO639_NOB = "nob"; // Norwegian Bokmål
	public static final String ISO639_NON = "non"; // Old Norse
	public static final String ISO639_NOR = "nor"; // Norwegian
	public static final String ISO639_NOV = "nov"; // Novial
	public static final String ISO639_NRM = "nrm"; // Narom
	public static final String ISO639_NTJ = "ntj"; // Ngaanyatjarra
	public static final String ISO639_NYA = "nya"; // Nyanja
	public static final String ISO639_NYS = "nys"; // Nyunga
	public static final String ISO639_OCI = "oci"; // Occitan
	public static final String ISO639_OFS = "ofs"; // Old Frisian
	public static final String ISO639_OJI = "oji"; // Ojibwa
	public static final String ISO639_OKM = "okm"; // Middle Korean
	public static final String ISO639_OOD = "ood"; // Tohono O'odham
	public static final String ISO639_ORI = "ori"; // Oriya
	public static final String ISO639_ORM = "orm"; // Oromo
	public static final String ISO639_OSP = "osp"; // Old Spanish
	public static final String ISO639_OSS = "oss"; // Ossetian
	public static final String ISO639_OSX = "osx"; // Old Saxon
	public static final String ISO639_OTA = "ota"; // Ottoman Turkish
	public static final String ISO639_PAM = "pam"; // Pampanga
	public static final String ISO639_PAN = "pan"; // Panjabi
	public static final String ISO639_PAP = "pap"; // Papiamento
	public static final String ISO639_PAU = "pau"; // Palauan
	public static final String ISO639_PCD = "pcd"; // Picard
	public static final String ISO639_PDC = "pdc"; // Pennsylvania German
	public static final String ISO639_PEO = "peo"; // Old Persian
	public static final String ISO639_PES = "pes"; // Iranian Persian
	public static final String ISO639_PHN = "phn"; // Phoenician
	public static final String ISO639_PIT = "pit"; // Pitta Pitta
	public static final String ISO639_PJT = "pjt"; // Pitjantjatjara
	public static final String ISO639_PLI = "pli"; // Pali
	public static final String ISO639_PMS = "pms"; // Piemontese
	public static final String ISO639_PMT = "pmt"; // Tuamotuan
	public static final String ISO639_PNT = "pnt"; // Pontic
	public static final String ISO639_PNW = "pnw"; // Panytyima
	public static final String ISO639_POC = "poc"; // Poqomam
	public static final String ISO639_POH = "poh"; // Poqomchi'
	public static final String ISO639_POL = "pol"; // Polish
	public static final String ISO639_POR = "por"; // Portuguese
	public static final String ISO639_PRG = "prg"; // Prussian
	public static final String ISO639_PRO = "pro"; // Old Provençal
	public static final String ISO639_PUS = "pus"; // Pushto
	public static final String ISO639_PUU = "puu"; // Punu
	public static final String ISO639_QUC = "quc"; // K'iche'
	public static final String ISO639_QUE = "que"; // Quechua
	public static final String ISO639_QUM = "qum"; // Sipacapense
	public static final String ISO639_QUV = "quv"; // Sacapulteco
	public static final String ISO639_RAP = "rap"; // Rapanui
	public static final String ISO639_RAR = "rar"; // Rarotongan
	public static final String ISO639_RCF = "rcf"; // Réunion Creole French
	public static final String ISO639_RGE = "rge"; // Romano-Greek
	public static final String ISO639_RHG = "rhg"; // Rohingya
	public static final String ISO639_RMI = "rmi"; // Lomavren
	public static final String ISO639_RMY = "rmy"; // Vlax Romani
	public static final String ISO639_ROH = "roh"; // Romansh
	public static final String ISO639_ROM = "rom"; // Romany
	public static final String ISO639_RON = "ron"; // Romanian
	public static final String ISO639_ROO = "roo"; // Rotokas
	public static final String ISO639_ROP = "rop"; // Kriol
	public static final String ISO639_RTM = "rtm"; // Rotuman
	public static final String ISO639_RUN = "run"; // Rundi
	public static final String ISO639_RUO = "ruo"; // Istro Romanian
	public static final String ISO639_RUP = "rup"; // Macedo-Romanian
	public static final String ISO639_RUQ = "ruq"; // Megleno Romanian
	public static final String ISO639_RUS = "rus"; // Russian
	public static final String ISO639_RUT = "rut"; // Rutul
	public static final String ISO639_RWR = "rwr"; // Marwari (India)
	public static final String ISO639_SAG = "sag"; // Sango
	public static final String ISO639_SAH = "sah"; // Yakut
	public static final String ISO639_SAN = "san"; // Sanskrit
	public static final String ISO639_SBF = "sbf"; // Shabo
	public static final String ISO639_SCN = "scn"; // Sicilian
	public static final String ISO639_SCO = "sco"; // Scots
	public static final String ISO639_SEI = "sei"; // Seri
	public static final String ISO639_SGA = "sga"; // Old Irish
	public static final String ISO639_SHI = "shi"; // Tachelhit
	public static final String ISO639_SID = "sid"; // Sidamo
	public static final String ISO639_SIN = "sin"; // Sinhala
	public static final String ISO639_SJD = "sjd"; // Kildin Sami
	public static final String ISO639_SLK = "slk"; // Slovak
	public static final String ISO639_SLV = "slv"; // Slovenian
	public static final String ISO639_SMA = "sma"; // Southern Sami
	public static final String ISO639_SME = "sme"; // Northern Sami
	public static final String ISO639_SMJ = "smj"; // Lule Sami
	public static final String ISO639_SMO = "smo"; // Samoan
	public static final String ISO639_SMS = "sms"; // Skolt Sami
	public static final String ISO639_SNA = "sna"; // Shona
	public static final String ISO639_SND = "snd"; // Sindhi
	public static final String ISO639_SOM = "som"; // Somali
	public static final String ISO639_SOT = "sot"; // Southern Sotho
	public static final String ISO639_SPA = "spa"; // Spanish
	public static final String ISO639_SQI = "sqi"; // Albanian
	public static final String ISO639_SRD = "srd"; // Sardinian
	public static final String ISO639_SRN = "srn"; // Sranan Tongo
	public static final String ISO639_SRP = "srp"; // Serbian
	public static final String ISO639_SSW = "ssw"; // Swati
	public static final String ISO639_STH = "sth"; // Shelta
	public static final String ISO639_STQ = "stq"; // Saterfriesisch
	public static final String ISO639_STR = "str"; // Straits Salish
	public static final String ISO639_SUN = "sun"; // Sundanese
	public static final String ISO639_SUX = "sux"; // Sumerian
	public static final String ISO639_SWA = "swa"; // Swahili
	public static final String ISO639_SWB = "swb"; // Maore Comorian
	public static final String ISO639_SWE = "swe"; // Swedish
	public static final String ISO639_SWH = "swh"; // Swahili (individual language)
	public static final String ISO639_SYC = "syc"; // Classical Syriac
	public static final String ISO639_SYR = "syr"; // Syriac
	public static final String ISO639_SZL = "szl"; // Silesian
	public static final String ISO639_TAH = "tah"; // Tahitian
	public static final String ISO639_TAM = "tam"; // Tamil
	public static final String ISO639_TAT = "tat"; // Tatar
	public static final String ISO639_TCS = "tcs"; // Torres Strait Creole
	public static final String ISO639_TEL = "tel"; // Telugu
	public static final String ISO639_TET = "tet"; // Tetum
	public static final String ISO639_TGK = "tgk"; // Tajik
	public static final String ISO639_TGL = "tgl"; // Tagalog
	public static final String ISO639_THA = "tha"; // Thai
	public static final String ISO639_TIG = "tig"; // Tigre
	public static final String ISO639_TIR = "tir"; // Tigrinya
	public static final String ISO639_TIV = "tiv"; // Tiv
	public static final String ISO639_TIW = "tiw"; // Tiwi
	public static final String ISO639_TKL = "tkl"; // Tokelau
	public static final String ISO639_TLH = "tlh"; // Klingon
	public static final String ISO639_TMR = "tmr"; // Jewish Babylonian Aramaic (ca. 200-1200 CE)
	public static final String ISO639_TOI = "toi"; // Tonga (Zambia)
	public static final String ISO639_TOJ = "toj"; // Tojolabal
	public static final String ISO639_TON = "ton"; // Tonga (Tonga Islands)
	public static final String ISO639_TPI = "tpi"; // Tok Pisin
	public static final String ISO639_TPN = "tpn"; // Tupinambá
	public static final String ISO639_TRU = "tru"; // Turoyo
	public static final String ISO639_TSD = "tsd"; // Tsakonian
	public static final String ISO639_TSN = "tsn"; // Tswana
	public static final String ISO639_TSO = "tso"; // Tsonga
	public static final String ISO639_TTC = "ttc"; // Tektiteko
	public static final String ISO639_TUK = "tuk"; // Turkmen
	public static final String ISO639_TUR = "tur"; // Turkish
	public static final String ISO639_TVL = "tvl"; // Tuvalu
	public static final String ISO639_TWI = "twi"; // Twi
	public static final String ISO639_TXB = "txb"; // Tokharian B
	public static final String ISO639_TYV = "tyv"; // Tuvinian
	public static final String ISO639_TZH = "tzh"; // Tzeltal
	public static final String ISO639_TZJ = "tzj"; // Tz'utujil
	public static final String ISO639_TZO = "tzo"; // Tzotzil
	public static final String ISO639_UDM = "udm"; // Udmurt
	public static final String ISO639_UGA = "uga"; // Ugaritic
	public static final String ISO639_UIG = "uig"; // Uighur
	public static final String ISO639_UKR = "ukr"; // Ukrainian
	public static final String ISO639_ULK = "ulk"; // Meriam
	public static final String ISO639_ULN = "uln"; // Unserdeutsch
	public static final String ISO639_UMB = "umb"; // Umbundu
	public static final String ISO639_URD = "urd"; // Urdu
	public static final String ISO639_USP = "usp"; // Uspanteco
	public static final String ISO639_UZB = "uzb"; // Uzbek
	public static final String ISO639_VAI = "vai"; // Vai
	public static final String ISO639_VEC = "vec"; // Venetian
	public static final String ISO639_VEN = "ven"; // Venda
	public static final String ISO639_VEP = "vep"; // Veps
	public static final String ISO639_VIE = "vie"; // Vietnamese
	public static final String ISO639_VIN = "vin"; // Vinza
	public static final String ISO639_VLS = "vls"; // Vlaams
	public static final String ISO639_VMA = "vma"; // Martuyhunira
	public static final String ISO639_VMB = "vmb"; // Mbabaram
	public static final String ISO639_VMK = "vmk"; // Makhuwa-Shirima
	public static final String ISO639_VMW = "vmw"; // Makhuwa
	public static final String ISO639_VOL = "vol"; // Volapük
	public static final String ISO639_VOR = "vor"; // Voro
	public static final String ISO639_VOT = "vot"; // Votic
	public static final String ISO639_VRO = "vro"; // Võro
	public static final String ISO639_WAL = "wal"; // Wolaytta
	public static final String ISO639_WAM = "wam"; // Wampanoag
	public static final String ISO639_WAQ = "waq"; // Wageman
	public static final String ISO639_WAR = "war"; // Waray (Philippines)
	public static final String ISO639_WAS = "was"; // Washo
	public static final String ISO639_WBP = "wbp"; // Warlpiri
	public static final String ISO639_WBW = "wbw"; // Woi
	public static final String ISO639_WIM = "wim"; // Wik-Mungkan
	public static final String ISO639_WIV = "wiv"; // Vitu
	public static final String ISO639_WLN = "wln"; // Walloon
	public static final String ISO639_WMT = "wmt"; // Walmajarri
	public static final String ISO639_WOL = "wol"; // Wolof
	public static final String ISO639_WRH = "wrh"; // Wiradhuri
	public static final String ISO639_WUU = "wuu"; // Wu Chinese
	public static final String ISO639_WYB = "wyb"; // Wangaaybuwan-Ngiyambaa
	public static final String ISO639_WYM = "wym"; // Wymysorys
	public static final String ISO639_XAL = "xal"; // Kalmyk
	public static final String ISO639_XAV = "xav"; // Xavánte
	public static final String ISO639_XCL = "xcl"; // Classical Armenian
	public static final String ISO639_XDC = "xdc"; // Dacian
	public static final String ISO639_XHO = "xho"; // Xhosa
	public static final String ISO639_XMF = "xmf"; // Mingrelian
	public static final String ISO639_XMW = "xmw"; // Tsimihety Malagasy
	public static final String ISO639_XNO = "xno"; // Anglo-Norman
	public static final String ISO639_XTA = "xta"; // Alcozauca Mixtec
	public static final String ISO639_XTO = "xto"; // Tokharian A
	public static final String ISO639_XVN = "xvn"; // Vandalic
	public static final String ISO639_YAO = "yao"; // Yao
	public static final String ISO639_YAP = "yap"; // Yapese
	public static final String ISO639_YDD = "ydd"; // Eastern Yiddish
	public static final String ISO639_YEJ = "yej"; // Yevanic
	public static final String ISO639_YID = "yid"; // Yiddish
	public static final String ISO639_YII = "yii"; // Yidiny
	public static final String ISO639_YIJ = "yij"; // Yindjibarndi
	public static final String ISO639_YMM = "ymm"; // Maay
	public static final String ISO639_YOR = "yor"; // Yoruba
	public static final String ISO639_YRL = "yrl"; // Nhengatu
	public static final String ISO639_YUA = "yua"; // Yucateco
	public static final String ISO639_YUE = "yue"; // Yue Chinese
	public static final String ISO639_ZAI = "zai"; // Isthmus Zapotec
	public static final String ISO639_ZAM = "zam"; // Miahuatlán Zapotec
	public static final String ISO639_ZAV = "zav"; // Yatzachi Zapotec
	public static final String ISO639_ZAZ = "zaz"; // Zari
	public static final String ISO639_ZEN = "zen"; // Zenaga
	public static final String ISO639_ZHA = "zha"; // Zhuang
	public static final String ISO639_ZHO = "zho"; // Chinese
	public static final String ISO639_ZKU = "zku"; // Kaurna
	public static final String ISO639_ZMK = "zmk"; // Mandandanyi
	public static final String ISO639_ZMX = "zmx"; // Bomitaba
	public static final String ISO639_ZPC = "zpc"; // Choapan Zapotec
	public static final String ISO639_ZPP = "zpp"; // El Alto Zapotec
	public static final String ISO639_ZPQ = "zpq"; // Zoogocho Zapotec
	public static final String ISO639_ZRP = "zrp"; // Zarphatic
	public static final String ISO639_ZTU = "ztu"; // Güilá Zapotec
	public static final String ISO639_ZTX = "ztx"; // Zaachila Zapotec
	public static final String ISO639_ZUL = "zul"; // Zulu
	public static final String ISO639_ZUN = "zun"; // Zuni
	
	public static final String ISO639_ATH = "ath"; // Athapascan languages
	public static final String ISO639_BAD = "bad"; // Banda languages
	public static final String ISO639_BER = "ber"; // Berber languages
	public static final String ISO639_BIH = "bih"; // Bihari languages
	public static final String ISO639_BNT = "bnt"; // Bantu languages
	public static final String ISO639_MNO = "mno"; // Manobo languages
	public static final String ISO639_MYN = "myn"; // Mayan languages
	public static final String ISO639_NAH = "nah"; // Nahuatl languages
	public static final String ISO639_SIO = "sio"; // Siouan languages
	public static final String ISO639_SMI = "smi"; // Sami languages
	
	public static final String NONSTD_ART_EUR = "Xeur"; // Europanto
	public static final String NONSTD_ART_ROM = "Xart-rom"; // Romanica
	public static final String NONSTD_ART_TOK = "Xart-tok"; // Toki Pona
	public static final String NONSTD_AST_LEO = "ast-leo"; // Leonese
	public static final String NONSTD_BAT_SMG = "bat-smg"; // Samogitian
	public static final String NONSTD_BNS = "Xbns"; // Binisayâ
	public static final String NONSTD_CHS = "chs"; // Chumash
	public static final String NONSTD_DOG = "Xdog"; // Dogon
	public static final String NONSTD_ELL_GRI = "ell-gri"; // Salentine Greek
	public static final String NONSTD_EML = "eml"; // Romagnolo
	public static final String NONSTD_FRA_JER = "fra-jer"; // Jèrriais
	public static final String NONSTD_FRI = "Xfri"; // Frisian
	public static final String NONSTD_GLO = "Xglo"; // Glosa
	public static final String NONSTD_KJL_ZKM = "kjl-zkm"; // Maikoti
	public static final String NONSTD_MUL = "Xmul"; // Translingual
	public static final String NONSTD_NAP_CAL = "nap-cal"; // Calabrese
	public static final String NONSTD_OCI_PRV = "oci-prv"; // Provençal
	public static final String NONSTD_POR_BR = "por-br"; // Brasilian Portuguese
	public static final String NONSTD_SIC = "sic"; // Malinguat
	public static final String NONSTD_SIMPLE = "Xsimple"; // Simple English
	public static final String NONSTD_STR_SAA = "str-saa"; // Saanich
	public static final String NONSTD_TWF_TAO = "twf-tao"; // Taos
	public static final String NONSTD_YUE_CAN = "yue-can"; // Cantonese
	
}
